### ISSUE TITLE
BUG: Adding a Mace as a weapon crashes the app

### ISSUE THREAD

**Issue by Clayseph** [kjintroverted/dragon-ui#33]
Selecting a mace as a weapon crashes the app

**Comment by kjintroverted** [comment]
Error on trying to [read weapon properties](https://github.com/kjintroverted/dragon-ui/blob/master/src/services/helper.js#L9). 

Some weapons have null properties so this function needs to account for that.

**Comment by kjintroverted** [comment]
![image](https://user-images.githubusercontent.com/17323188/64873735-b9b8d200-d617-11e9-90fb-049f7310cc1f.png)

Battleaxe ✅ 
Flail ❌
